### ISSUE TITLE
Add JUnit XML output option

### ISSUE THREAD

**Issue by lvh** [cloverage/cloverage#116]
@ryfow started work on this a while ago: https://github.com/lshift/cloverage/pull/80

That PR got closed because it had an outstanding comment. The original author appears unresponsive (not a criticism; PR has been up for over a year). Other people have expressed interest in the feature (#103). This issue is intended to track progress on that feature without having to keep the PR open.

One solution would be to start from that branch and to address the PR comment.

**Comment by ryfow** [comment]
Sorry for not getting back earlier. I'm swamped for the time being, so I probably won't be able to update the PR soon. Hopefully someone will be able to pick up where I left off.
