### ISSUE TITLE
0% coverage report if any namespace requires itself

### ISSUE THREAD

**Issue by lvh** [cloverage/cloverage#122]
Not very high priority because linters will presumably catch this. See #117 for original report.

**Comment by JacekLach** [comment]
Intuition is that the namespace sorting algorithm (that enforces they get
instrumented in the right order) gives up when it hits a cycle, and returns
an empty list. So no namespace gets instrumented, resulting in 0%

**Comment by lvh** [comment]
Yep, that makes a lot of sense. It seems like a simple exception in the nil case would cover it :)
