### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by palfrey** [cloverage/cloverage#128]
As noted in https://github.com/cloverage/cloverage/issues/103#issuecomment-236608369 now this project has gotten opened up to the wider community, it could do with a CoC. It should hopefully just encode the existing community spirit, but good to have some actual words about it as well. I'll go and find some good existing sources of said...

**Comment by rm-hull** [comment]
The ubuntu one always struck me as entirely reasonable and easy-to-comprehend: http://www.ubuntu.com/about/about-ubuntu/conduct

**Comment by lvh** [comment]
I've had good experiences with http://contributor-covenant.org/ on a few projects I've worked on. I'm unfamiliar with the Ubuntu one. My first thought is: do they encourage other projects to incorporate it? (That is the Contributor Covenant's reason for existence.)

**Comment by lvh** [comment]
Apparently it does allow modification:

> The Ubuntu Code of Conduct is licensed under the Creative Commons Attribution-Share Alike 3.0 license. You may re-use it for your own project, and modify it as you wish, just please allow others to use your modifications and give credit to the Ubuntu Project!

At the risk of turning this into a bikeshed, I have a preference for the one designed to be co-opted by projects like ours vs one we'd need to adapt ourselves.
