### ISSUE TITLE
Get rid of jaceklach/cloverage fork metadata

### ISSUE THREAD

**Issue by lvh** [cloverage/cloverage#129]
This continues to show master as being ahead/behind the previous-previous-but-not-original repo. Since this is the one true blessed repo now, we should get rid of that connection, since it's just confusing.

I think this can be done after the fact by GitHub support or by deleting the original repo. I'm happy to do the support route.

@JacekLach Any thoughts/objections?

**Comment by lvh** [comment]
When I tried to move the releng notes, GitHub helpfully thought I wanted the PR to target the JacekLach fork: https://github.com/JacekLach/cloverage/pull/27 

I'll contact GitHub support.

**Comment by lvh** [comment]
I have asked GitHub to resolve this.

**Comment by JacekLach** [comment]
No objections from me regarding removing the metadata, BTW.

**Comment by lvh** [comment]
This has now been resolved.
