### ISSUE TITLE
Cloverage can't find .cljc files

### ISSUE THREAD

**Issue by rationalism** [cloverage/cloverage#130]
Cloverage only looks for files with a .clj (Clojure) extension, not a .cljc (shared between both Clojure and ClojureScript) extension. I worked around this by creating symbolic links for each .cljc file to a corresponding .clj file, but that's a bit awkward.

**Comment by rm-hull** [comment]
Support for .cljc files was fixed in #97, and will be available in the next release (available hopefully quite soon).

In the meantime, you can use the latest snapshot version by calling cloverage as: `CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage`

**Comment by rm-hull** [comment]
@rationalism - 1.0.7 has now been released, if you would care to try it out.
@lvh - think this ticket can be closed as a dupe

**Comment by lvh** [comment]
agreed
