### ISSUE TITLE
Fix CircleCI build

### ISSUE THREAD

**Issue by lvh** [cloverage/cloverage#134]
https://github.com/cloverage/cloverage/pull/133 removed the CircleCI badge because it was pretty broken (not doing new builds, only having a few really old ones, still pointing to lshift/cloverage). I'm happy to add the badge back if someone fixes the build.

cc @rm-hull @drazisil

**Comment by drazisil** [comment]
@lvh Only an admin can add a project to CircleCi, the expectation was that would be part of the PR merge, sorry for not being clear on that.

**Comment by lvh** [comment]
OK; do you know why there are old builds there? It seems like someone must have enabled it before? I had admin powers now.

**Comment by drazisil** [comment]
It looks like the last one was done by @JacekLach. However, if they told the project to stop building, it would, until an admin gives CircleCi a new key/web hook.

**Comment by lvh** [comment]
OK, I told CircleCI to build, and it looks like it's doing something now.

**Comment by drazisil** [comment]
https://circleci.com/gh/cloverage/cloverage/5#tests/containers/0 Looks good to me, except for your missing `breakme` command :)

**Comment by JacekLach** [comment]
Not convinced building on both travis and circle is providing any value?

I think we've tried both circle and travis before ending up on travis for reasons I can't recall anymore.

**Comment by lvh** [comment]
I've fixed the build.

@JacekLach You're right hat I don't think it provides any extra value right now; but it also doesn't really hurt, and IIUC a few contributors are also now at CircleCI, so they're a friendly company :)

**Comment by lvh** [comment]
Another advantage is that this gives us extra free builders; so if we wanted a place to run hard-to-reproduce or hard-to-minify test cases on a particular repo or something :)
