### ISSUE TITLE
Pass :cloverage opts in project.clj to -main

### ISSUE THREAD

**Issue by rm-hull** [cloverage/cloverage#155]
It would be handy to be able to set opts in my _project.clj_ such that when I run `lein cloverage`, they are automatically passed through to the [-main](https://github.com/cloverage/cloverage/blob/master/cloverage/src/cloverage/coverage.clj#L192) method.

For example, something like:

``` clojure
(defproject myproj "0.5.2"
  :description "..."
  :url "..."
  ; ...
  ; ...
  :cloverage {
    :runner :midge
    :output [:lcov :emma :junit]
    :fail-threshold 90
    :extra-test-ns [ 'some.namespace ]})


```

**Comment by eurythmia** [comment]
using :profiles this appears to be fixed now in version 1.0.11-SNAPSHOT. Can we mark this as resolved?

**Comment by lvh** [comment]
Yup! That's released now.

**Comment by eurythmia** [comment]
thanks :-)
