### ISSUE TITLE
Insecure HTTP repository

### ISSUE THREAD

**Issue by tiagofabre** [cloverage/cloverage#199]
I Installed cloverage adding adding it to my **_~/.lein/profiles.clj_** and running `lein deps`
(follow my _**~/.lein/profiles.clj**_)
```
{:user {:plugins [[cider/cider-nrepl "0.8.1"]
                  [jonase/eastwood "0.2.1"]
                  [lein-cloverage "1.0.2"]]}}
```
After that I am trying to run `lein cloverage` but the output is:

```
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.
```

What the FAQ says about that is:

```
**Q:** I got `Tried to use insecure HTTP repository without TLS`, what is that about?
**A:** This means your project was configured to download dependencies
from a repository that does not use TLS encryption. This is very
insecure and exposes you to trivially-executed man-in-the-middle attacks.
In the rare event that you don't care about the security of the machines
running your project, you can re-enable support for unprotected repositories
by putting this in your `project.clj` file:

    ;; never do this
    (require 'cemerick.pomegranate.aether)
    (cemerick.pomegranate.aether/register-wagon-factory!
     "http" #(org.apache.maven.wagon.providers.http.HttpWagon.))

It's also possible you have a dependency which includes a reference to
an insecure repository for retrieving its own dependencies. If this
happens it is strongly recommended to add an `:exclusion` and report a
bug with the dependency which does this.
```
I am new in clojure so I have no idea how to solve that even with the FAQ answer (it is not clear for me, my project.clj has nothing similar). How can I solve that is it a cloverage problem or not?

**Comment by lvh** [comment]
Hey: I'm unable to reproduce this. There are no insecure references within cloverage; cloverage always relies on lein to acquire dependencies.

Can you narrow it down to just cloverage to make sure this is actually what's causing the problem?

**Comment by lvh** [comment]
(To do that: remove everything besides cloverage, see if problem persists.)

**Comment by tiagofabre** [comment]
The problem were in my `project.clj`. It had this key `:repositories {"stuartsierra-releases" "http://stuartsierra.com/maven2"}`and I only changed to `https` and solved the problem.

Thank you!
