### ISSUE TITLE
All nses are excluded when there is no ns-exclude-regex

### ISSUE THREAD

**Issue by ProjectFrank** [cloverage/cloverage#209]
When `lein cloverage` is called without any `ns-exclude-regex`, all namespaces get excluded except for the additional instrumented namespaces. (`1.0.11-SNAPSHOT`)

**Comment by lvh** [comment]
Thanks! I'm assuming you're sitll passing the option, just not with a value and this is happening because nothing matches the empty string?

I'm not super sure that's a bug. What behavior would you like to see?

**Comment by ProjectFrank** [comment]
This happens when the option is not passed in at all. The workaround I'm currently using is to pass in a regex that won't match anything.

**Comment by lvh** [comment]
Uh, so what you're saying is the current snapshot just... doesn't include any namespaces? Yeah, that's not great :D

**Comment by ProjectFrank** [comment]
It looks like this is the culprit: https://github.com/cloverage/cloverage/blob/master/cloverage/src/cloverage/coverage.clj#L251

`find-nses` returns all the nses when it is passed an empty collection of `exclude-regex` regexes, so all nses are getting removed here

**Comment by lvh** [comment]
FWIW: I don't have the resources to fix bugs but I'd be happy to review fixes and cut releases :)

**Comment by ProjectFrank** [comment]
Actually, this seems to be fixed in https://github.com/cloverage/cloverage/pull/207. Has that change been incorporated into the latest snapshot release?

**Comment by lvh** [comment]
My understanding is that snapshot releases are cut by Travis whenever a master build finishes, so, ought to be.

**Comment by lvh** [comment]
Oh sorry: #207 was merged right now -- so try again with the _most recent_ SNAPSHOT :)

**Comment by ProjectFrank** [comment]
yep that fixes it.
