### ISSUE TITLE
It's not working on Java 10

### ISSUE THREAD

**Issue by LukasRychtecky** [cloverage/cloverage#211]
Bultitude is using ouf of date dynapath (there is a waiting PR https://github.com/Raynes/bultitude/pull/31). Until it will be merged, you can add `[org.tcrawley/dynapath "1.0.0"]` into project's `:dependencies` to fix ip.

**Comment by lvh** [comment]
Thanks for the report! FWIW: I'm happy to review/merge PRs but don't have time to actively maintain this.

**Comment by rm-hull** [comment]
Anthony Grimes (@Raynes) passed away in 2016. I doubt anyone else has commit rights on that repo, so it is unlikely that the PR is going to get merged as-is. 

https://cemerick.com/2016/12/07/rip-anthony-grimes/

**Comment by LukasRychtecky** [comment]
I'm so sorry, I didn't know it.

Anyway, do you think who has the right? Otherwise we will fork it, probably.

**Comment by TimoFreiberg** [comment]
So it looks like a possible solution would be to
1. fork bultitude
2. update the dynapath dependency of the fork
3. create a PR here that moves the bultitude dependency to the fork
correct?

**Comment by LukasRychtecky** [comment]
It seems that no one else has the rights for the repo. Thus @TimoFreiberg is right, let's do it. @TimoFreiberg Do you want to do it, or should I?

**Comment by lvh** [comment]
We should use @tobias' fork if at all possible. Toby's a nice guy, done a lot of Java 9/10 work, and a gazillion forks with no idea of which one to use helps no-one.

**Comment by tobias** [comment]
Howdy @lvh! I don't actually maintain a fork, I just forked the repo to create a PR to update the dynapath dependency. A quick [search on Clojars](https://clojars.org/search?q=bultitude) doesn't reveal any published forks, so if it's important to cloverage, you may want to have your own fork. I suspect others that depend on bultitude would appreciate it, since it looks like no one has come forward to do so.

**Comment by lvh** [comment]
Neat; thanks for chiming in. Good job on not accreting more responsibilities :D

OK, who wants to be a hero? @LukasRychtecky? @TimoFreiberg? ;)

**Comment by TimoFreiberg** [comment]
I don't like the sound of "hero", but it looks like a reasonably small commitment :)
