### ISSUE TITLE
Please release 1.0.11

### ISSUE THREAD

**Issue by positron** [cloverage/cloverage#213]
The documentation on the README with all the fancy new options that cloverage supports does not match the released version (1.0.10) that the README tells you to use.

**Comment by lvh** [comment]
I'll see if I can figure out how, but as a workaround for right now: the SNAPSHOT releases should be up to date with master.

**Comment by lvh** [comment]
FWIW: here's why cutting a release is hard. Both cloverage and the plugin are configured to use Clojars via a username and password with no signing. This is why master builds are sent to Clojars as snapshots. I don't have that password. Travis has it but it seems skeevy to try to exfiltrate it. If I edit out that line, the deployed image isn't what was in master at the time.

One solution might be for Travis to manually generate a `profiles.clj` when it's about to cut a release?

**Comment by lvh** [comment]
https://clojars.org/cloverage/versions/1.0.11 :tada:
