### ISSUE TITLE
Invalid lcov format?

### ISSUE THREAD

**Issue by lukaszkorecki** [cloverage/cloverage#225]
Hi 👋 !

My team recently started using CodeClimate - and I was happy to discover that we can use its coverage reporting via lcov format. Here's the setup (assumes that everything is configured on CodeClimate side):

https://github.com/lukaszkorecki/codeclimate-kibit/blob/73491d0a1d280a35ef4d1496d1e93cd2fb9de911/.circleci/config.yml#L43-L48

```bash
./cc-test-reporter before-build
lein trampoline cloverage --lcov --no-text --no-html --no-summary -o $PWD
testRes=$?
mkdir -p coverage
sed 's/^SF:/SF:src\//' lcov.info > coverage/lcov.info
./cc-test-reporter after-build --coverage-input-type lcov --exit-code $testRes 
```

The line with `sed` invokation addresses the issue I found. Generated lcov report doesn't include the `src/` part of the path to the files found during test run:

```
$ grep SF: lcov.info
SF:codeclimate/reporter.clj
SF:codeclimate/ignore.clj
SF:codeclimate/kibit.clj
```

I'm not really familiar with lcov format, but it looks like it's a bug - given that the coverage report runs from the root of the project, I'd expect the paths in the coverage report to be also relative to the root.

If it's a real issue I'm more than happy to fix this 👍 or add a command line flag to optionally add a prefix to paths generated in lcov format.

**Comment by lvh** [comment]
The `sed` line is to fix the addition of the `src` I take it?

**Comment by lukaszkorecki** [comment]
@lvh yes, that is correct

**Comment by lvh** [comment]
Cool. I can cut releases and review PRs, but I don't have much resources to devote outside of that. Does sound like a bug though! So if you write a fix I'll carry it from there :)

**Comment by lukaszkorecki** [comment]
Makes sense - I hope to get some time soon and get a PR with the fix 👍 Thanks!
