### ISSUE TITLE
Inclusion of venantius/ultra in cloverage's dependencies

### ISSUE THREAD

**Issue by gordonsyme** [cloverage/cloverage#228]
Hi there, thanks for providing cloverage, we use it pretty extensively and it's great!

I've noticed that recent versions of cloverage (from [1.0.11](https://clojars.org/cloverage/versions/1.0.11) to [1.0.13](https://clojars.org/cloverage/versions/1.0.13) ) now include [venantius/ultra](https://github.com/venantius/ultra) in their dependencies. [1.0.10](https://clojars.org/cloverage/versions/1.0.10) and before don't.

We use leiningen's `:pedantic? :abort` in our projects and ultra's dependencies can add quite a few version conflicts.

There isn't any mention of ultra in cloverage's git history, could it be that ultra is being accidentally injected via a `.lein` profile when the releases are being made?

**Comment by gordonsyme** [comment]
Sure, this is the part of the tree rooted at cloverage:
```
 [cloverage "1.0.13" :scope "test" :exclusions [[org.clojure/clojure] [instaparse] [org.clojure/tools.cli] [org.clojure/tools.reader] [org.clojure/tools.logging]]]
   [org.clojure/data.json "0.2.6"]
   [org.clojure/data.xml "0.0.8" :scope "test"]
   [riddley "0.1.14"]
   [timofreiberg/bultitude "0.2.10" :scope "test"]
     [org.tcrawley/dynapath "1.0.0" :scope "test"]
   [venantius/ultra "0.5.2" :scope "test"]
     [grimradical/clj-semver "0.3.0" :scope "test" :exclusions [[org.clojure/clojure]]]
     [io.aviso/pretty "0.1.30" :scope "test"]
     [mvxcvi/puget "1.0.1" :scope "test"]
       [fipp "0.6.6" :scope "test"]
         [org.clojure/core.rrb-vector "0.0.11" :scope "test"]
       [mvxcvi/arrangement "1.1.0" :scope "test"]
     [mvxcvi/whidbey "1.3.0" :scope "test"]
     [org.clojars.brenton/google-diff-match-patch "0.1" :scope "test"]
     [robert/hooke "1.3.0" :scope "test"]
     [venantius/glow "0.1.4" :scope "test" :exclusions [[hiccup] [garden]]]
       [clj-antlr "0.2.3" :scope "test"]
         [org.antlr/antlr4-runtime "4.5.3" :scope "test"]
         [org.antlr/antlr4 "4.5.3" :scope "test"]
```

**Comment by lvh** [comment]
That's bizarre. I definitely have ultra in _my_ profiles, but I have no idea why it'd show up in the dep tree.

**Comment by nwjsmith** [comment]
@gordonsyme @lvh the dependency tree as of 62557e1ba2215b99fde9aa5a2bb23dc5f7d3e583:

```
 [clojure-complete "0.2.5" :exclusions [[org.clojure/clojure]]]
 [nrepl "0.6.0" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.10.1"]
   [org.clojure/core.specs.alpha "0.2.44"]
   [org.clojure/spec.alpha "0.2.176"]
 [org.clojure/data.json "0.2.6"]
 [org.clojure/data.xml "0.0.8"]
 [org.clojure/java.classpath "0.3.0"]
 [org.clojure/tools.cli "0.4.2"]
 [org.clojure/tools.logging "0.5.0"]
 [org.clojure/tools.namespace "0.3.1"]
 [org.clojure/tools.reader "1.3.2"]
 [riddley "0.2.0"]
 [slingshot "0.12.2"]
```
Looks like this issue has been resolved.

**Comment by nwjsmith** [comment]
Upon further inspection, it looks like this was an issue specifically with [1.0.12](https://clojars.org/cloverage/versions/1.0.12) and [1.0.13](https://clojars.org/cloverage/versions/1.0.13), but no later versions (see the list of dependencies for those artifacts).

**Comment by gordonsyme** [comment]
Thanks @nwjsmith, from what I remember it was ultra's behaviour of injecting itself as a dependency when used as a plugin that caused this.
