### ISSUE TITLE
Coverage within `for` comprehensions is always partial

### ISSUE THREAD

**Issue by johnwright** [cloverage/cloverage#23]
Use of `for` in code under test seems to always result in an orange, partially-covered state in the coverage report.

e.g. given a namespace containing:

    (def foo
      (for [x [1 2 3]]
        x))
    
    (println foo)

...the line containing the `for` lights up orange, while the `def` and `println` lines are green.

**Comment by MichaelBlume** [comment]
Yeah, I'm running into this.

Best thing I can think of -- on any invocation of `for` or `doseq`, macroexpand, walk the generated code for calls to (if (clojure.core/chunked-seq? _) tf ff) and replace them with ff

**Comment by MichaelBlume** [comment]
I made what I think is a valiant attempt at fixing this bug here https://github.com/MichaelBlume/cloverage/commit/d19b84961c50cb2a005a53f32624132ef4e2f637 but it's failing with errors I don't understand. Maybe someone who understands the instrumentation process better can help me debug it?

**Comment by MichaelBlume** [comment]
Ha, actually I think I fixed it, pull to follow =)
