### ISSUE TITLE
Cloverage dramatically underreports form coverage

### ISSUE THREAD

**Issue by plexus** [cloverage/cloverage#233]
If you look at [these coverage results](https://codecov.io/gh/lambdaisland/kaocha-cloverage/src/master/src/kaocha/plugin/cloverage.clj), they have 100% line coverage but only 50% form coverage. Some of that can be chalked up to macros, but quite a few of those lines are bog-standard Clojure code that isn't even doing that much.

I can not think of a single test to add that would exercise any more code paths than the ones that are exercised now.

Can't we do better?

**Comment by lvh** [comment]
That link doesn't work for me.

**Comment by plexus** [comment]
What does it look like for you? I just tried in an anonymous browser window and it seems to be public...

**Comment by plexus** [comment]
The problem was that my tests were themselves invoking Cloverage, which unsurprisingly messed up the results. Sorry for the noise!

**Comment by plexus** [comment]
```
|-------------------------+---------+---------|
|               Namespace | % Forms | % Lines |
|-------------------------+---------+---------|
| kaocha.plugin.cloverage |  100.00 |  100.00 |
|-------------------------+---------+---------|
|               ALL FILES |  100.00 |  100.00 |
|-------------------------+---------+---------|
```

:smile:

**Comment by lvh** [comment]
Hooray! Glad it got resolved :)
