### ISSUE TITLE
Test calling wrong function

### ISSUE THREAD

**Issue by thumbnail** [cloverage/cloverage#247]
Given a file using java's interop and defining a function `new`, `lein cloverage` might call the wrong function. I noticed this only happens when the file is loaded early on (in `dev/user.clj` for example) .

`lein test` will always succeed (calling the right `new`-fn).
`lein cloverage` will call the redefined function for the interop (instead of clojure's new), causing unexpected behavior.

### Test case
I have setup a minimum test case here: https://github.com/thumbnail/cloverage-bug; mirrored version of the repo can be found here: [cloverage-bug-1.0.zip](https://github.com/cloverage/cloverage/files/3186688/cloverage-bug-1.0.zip)

In this case i defined a fn `new` with a different arity; causing an `clojure.lang.ArityException: Wrong number of args`. when running `lein cloverage`. note that running `lein test` will run successfully.

Notice that the test and cloverage will both run if `dev/user.clj`. as noted in the README.md of the example repo

 - It seems that functions required / referenced in `user.clj` are loaded before cloverage; causing them not to be wrapped?

**Comment by lvh** [comment]
Heya! Just to set expectations here:

1. I really appreciate you taking the time to make a reproducer.
2. I'm doing project management stuff like code review and releases but I don't have time to develop fixes.

**Comment by thumbnail** [comment]
Hey @lvh, thanks for that. Currently I refrain from using `user.clj` and cloverage together in a project; which prevents the issue as a whole. I might give this a shot in the future if it starts bothering me more.

**Comment by thumbnail** [comment]
I tried the repro and confirmed that the bug has indeed been solved! Thanks!

**Comment by lvh** [comment]
Sweet, thanks for double checking :)
