### ISSUE TITLE
Difference between % Forms and % Lines

### ISSUE THREAD

**Issue by p1mps** [cloverage/cloverage#252]
As the title says, what is the difference between the two columns in the table results? % Lines I understand of course but what about the other?

**Comment by lvh** [comment]
"Forms" are a Clojure term: https://clojure.org/reference/evaluation

Hope that helps, let me know if it doesn't.

**Comment by p1mps** [comment]
It doesn't, sorry :\. I still don't understand the difference between the two (though I know what forms and evaluation are in clojure FYI :)).

**Comment by lvh** [comment]
```clojure
(or (a)
    (b) (c) (d))
```

Let's say `(a)` returns true. b,c,d  are never evaluated. This snippet has 50% line coverage (there are two lines, one is evaluated), but far less form coverage (5 forms, 1 partial (or), 1 entirely, 3 not at all evaluated), resulting in 20% form coverage (or 40% including partials).

**Comment by p1mps** [comment]
Thank you for the explanation and thank you very much for your work!
