### ISSUE TITLE
Consider dropping AOT compiled tools.reader

### ISSUE THREAD

**Issue by plexus** [cloverage/cloverage#268]
Cloverage packs an AOT compiled version of clojure.tools.reader into the jars released to Clojars. This seems to have started in 2015 as a response to others adding AOT compiled libraries to their jars, notably Riemann. The reason was to make sure a specific, recent enough version would be used, but the result is that it has become impossible to control which version will be used, as you don't know which one will come first on the classpath.

This came up because kaocha-cloverage would emit warnings coming from tools.reader, even though the dependency tree showed a version of tools.reader that should have had these warnings fixed. After some digging it turned out Cloverage was the culprit.

@lvh seems like you are keeping the lights on here, would you consider dropping the inclusion of AOT'd tools.reader? It causes more problems and confusion than it solves. I also think that now that five years have passed perhaps the concerns over an outdated tools.reader version are somewhat lessened.

```
commit af9f3353adbf611fa5e141bfa3f018daf2a4511d
Author: Dominic LoBue <dominic.lobue@...>
Date:   Sat Jun 20 04:35:46 2015 -0700

    AOT compile tools.reader for version guarantees
    
    Older versions of clojure.tools.reader increase all line numbers by one.
    This results in odd looking reports where you have comments or blank
    lines showing as missing test coverage or weirder still as being covered
    if you have one of these older versions of clojure.tools.reader being
    pulled in transitively by another dependency.
    
    AOT compilation of tools.reader is necessary because configuring
    :exclusions for tools.reader on those dependencies which pull in the old
    version is ineffective when that dependency is using AOT (case in point:
    riemann). Unfortunately leiningen isn't doing the smart thing of using
    the newer but uncompiled version of a dependency yet. The only work
    around is fragile and untenable with a CI service. See the following
    github issues for more info:
    https://github.com/technomancy/leiningen/issues/1879
    https://github.com/technomancy/leiningen/issues/1858
```

**Comment by lvh** [comment]
Hm. I agree with your general assertion we should fix something, but I'm concerned just getting rid of the vendored version is bad too. Even if tools.reader is de facto much better about backwards compatibility these days, cloverage is an exception-catching machine (in the sense of "exception to the rule" not "Throwable") that relies on a lot of subtle details of a lot of progressively aging software.

Why is the right answer not using mranderson or whatever to vendor a specific version?

Either way, keeping the lights on is a good way to put it. I'll be happy to review PRs, maybe cut releases, but I don't have resources to actually devote to development (which cloverage desperately needs IMO).

**Comment by matt-y** [comment]
Combining the `:aot [clojure.tools.reader]` removal with a version bump I think would be fine. The main reason for not :aot-ing a dependency is that it can cause issues for downstream users as we see here. For me, that's enough reason to look into its removal. 

Looking at the commit where this was added seems to imply it was `:aot`'d to minimize bug reports from downstream sources using old reader versions, rather than a true reliance on specific functionality as the version being :aot'd has been bumped over the years. @lvh What would you like to do?

**Comment by lvh** [comment]
If the tests are happy I'm happy :)
