### ISSUE TITLE
unclear or misleading documentation in blog post

### ISSUE THREAD

**Issue by jimka2001** [cloverage/cloverage#270]
I was setting up test coverage according to [this blog post](https://blog.jeaye.com/2016/12/29/clojure-test-coverage/) and I feel like I'm almost there.  But some explanation in the post is confusing.

It specifies I can create a *badge* in the README.md file by inserting the following.

```
[![codecov](https://codecov.io/gh/USERNAME/PROJECT-NAME/branch/master/graph/badge.svg)]
 (https://codecov.io/gh/USERNAME/PROJECT-NAME)
```
However it doesn't indicate how to figure out the PROJECT-NAME nor USERNAME

I notice the code for registering the coverage data does not take either piece of information as arguments, so they must be calculated in some secret way.

```
after_success:
- lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
```

My user name is different depending on where I logged in from.  Furthermore several different people have permission to push to my git repo.  I don't know the name of the unix user who is the actual one running the ci pipeline And the repo is world-readable, so anyone can view the README.md file.     So who is the user?

If someone could clarify this, it would be really great.

I'm not sure if the specifics of my particular project would be helpful, in a large sense my questions are independent of my particular project.  Nevertheless, I'll provide the information in case they are helpful.

My project is at: https://gitlab.lrde.epita.fr/jnewton/clojure-rte

**Comment by lvh** [comment]
I don't control that blog post, so I can't fix it, but: the PROJECT-NAME and USERNAME are GitHub user/org name and project name, so clojure-rte and jnewton in your case. You should be able to copy the link to the badge from the codecov page.
