### ISSUE TITLE
Installation instructions unclear 

### ISSUE THREAD

**Issue by matt-y** [cloverage/cloverage#283]
Hello, I'm a bit new to clojure and got tripped up on cloverage's installation instructions with my lein project. 

I'd like to suggest that the installation portion of the `README` be slightly revamped to cover both of the following scenarios, but also with usable snippets to make installation much easier. 

For lein: 
1. Global cloverage install into `.lein/profiles.clj` _(this file does not currently exist on my system, and the current instructions don't specify that this is actually a global installation method)_
2. Per-Project cloverage install using the lein `:profiles` mechanism in a project's `project.clj` file, or via the `:plugins` mechanism, ex: `:plugins [[lein-cloverage "1.1.2"]]`

I'd also suggest the clojar link be moved up out of the install section. It isn't directly copyable, and might be more useful in the section with the travis / circleCI status. 

Thank you for the hard work!

**Comment by matt-y** [comment]
An additional question I had was whether or not I could include cloverage as a `:plugin` in the `:test` profile, which should be included during `lein test`. Is that possible? It seems to only work when included under the `:user` profile when the `:profile` mode of inclusion is used.

**Comment by lvh** [comment]
> An additional question I had was whether or not I could include cloverage as a `:plugin` in the `:test` profile, which should be included during `lein test`. Is that possible? It seems to only work when included under the `:user` profile when the `:profile` mode of inclusion is used.

Assuming `:plugin` is just a typo (you want `:plugins`, plural): `lein test` does two things: run leiningen's test runner, and activate the `:test` profile. So you're right that it will make cloverage _available_, but that doesn't mean it will _run_. If you want cloverage to run automatically when you run your tests, you'll have to override the `test` command, likely with an alias in your project.clj. I would generally advise you against messing with lein's builtin special behaviors, like lein repl, lein test, etc.

For more details see https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md.

The rest of your changes sound great and I'd be happy to take a PR.
