### ISSUE TITLE
defonce forms are instrumented incorrectly

### ISSUE THREAD

**Issue by camsaul** [cloverage/cloverage#294]
Code coverage reports that expression inside the `defonce` form is not covered (red), and that the conditional branches are not fully covered (yellow):

![image](https://user-images.githubusercontent.com/1455846/87836733-f06a0500-c845-11ea-9419-ba00fa374899.png)

`defonce` forms like

```clj
(defonce events-initialized?
  (atom nil))
```

expand to 

```clj
(let [v# (def events-initialized?)]
  (when-not (.hasRoot v#)
    (def events-initialized? (atom nil)))
```

This is my theory of what's happening:

1.  The form is instrumented.
2.  The namespace is evaled and and `events-initialized?` is set to `(atom nil)`. Coverage is not being recorded at this point.
3.  Tests run and coverage is starting to be recorded, but since the var already `.hasRoot` the conditional branch is not taken a second time
4.  The reports falsely report that this code was never executed

Does that sound right? 

I'm not sure what the best way to approach this issue is. It seems like ideally we'd want to make some changes so we start recording what gets evaluated right away, right after instrumentation before evaling any source files. Not sure how big of a change that would end up being. I would be happy to submit a PR if it's not too complicated.

**Comment by camsaul** [comment]
The same issue applies to the dispatch function of a `defmulti` form since `defmulti` behaves as if it were defined by `defonce`

**Comment by lvh** [comment]
This sounds plausible; the presumably correct approach is to specialcase `defonce` the way a number of other forms are specialcased.

**Comment by lvh** [comment]
Incidentally defmulti is already specialcased?
