### ISSUE TITLE
Repeated steps in build pipeline

### ISSUE THREAD

**Issue by cksharma11** [cloverage/cloverage#295]
I've seen few repeated steps in the circle-ci pipeline
More you can refer to the attached screenshot.

It can be intensional but just raising a point.

<img width="1377" alt="Screenshot 2020-07-29 at 11 40 45 AM" src="https://user-images.githubusercontent.com/22887527/88763393-b1ff0f00-d190-11ea-9531-fb8d5bbc8916.png">

**Comment by lvh** [comment]
Are you referring to there being multiple instances of `eastwood` and `kibit`?

**Comment by cksharma11** [comment]
> Are you referring to there being multiple instances of `eastwood` and `kibit`?

Yes.

**Comment by lvh** [comment]
One set is for cloverage, the other is for lein-cloverage :)
