### ISSUE TITLE
Error encountered performing task 'cloverage' with profile(s): 'base,system,user,provided,dev' Suppressed exit

### ISSUE THREAD

**Issue by cksharma11** [cloverage/cloverage#296]
I'm able to run the coverage but getting this error while running -lein with-profile +test cloverage

The problem it creating for me is the exit code 1 because of the error.

**Comment by lvh** [comment]
Do you have a minimal reproducer for this? That should only happen in ancient versions of lein or if there's actually an error.

**Comment by cksharma11** [comment]
@lvh Thanks for reply. 
Yes you are right it was happening due to the actual error. I found out the error. There were couple of tests cases which were causing the problem.

Thank you. you can close the issue.
