### ISSUE TITLE
lein test passing all the tests but with cloverage some tests are failing 

### ISSUE THREAD

**Issue by cksharma11** [cloverage/cloverage#300]
I'm facing a problem similar to https://github.com/cloverage/cloverage/issues/52

when I'm running the lein test all tests are passing 
but with when I'm running cloverage 4 of my tests are failing 

The main reason of my tests getting failed is it's calling the mock 2 times instead of once.

**Comment by lvh** [comment]
Can you try the current -SNAPSHOT?

**Comment by cksharma11** [comment]
@lvh  Thank you for the work

I'm getting the following error 
```
Dependency resolution error
				Error synchronising /Users/cksharma/projects/OTR/deal-picker/backend/project.clj:
				Could not find artifact lein-cloverage:lein-cloverage:jar:1.2.0-SNAPSHOT in clojars (https://repo.clojars.org/)
```
with `[lein-cloverage "1.2.0"]`

**Comment by cksharma11** [comment]
> Can you try the current -SNAPSHOT?

@lvh Thanks for the work.
