### ISSUE TITLE
Anticipating :eftest runner, please release 1.2.2

### ISSUE THREAD

**Issue by enspritz** [cloverage/cloverage#316]
If and when you're ready -- We are looking forward to the `:eftest` runner. Thanks kindly!

Also, the cloverage versions stated at the beginning of the README.md are apparently not in sync.
Clojars reports `1.2.1` which is accurate, while the Installation section recommends `1.1.2`..

**Comment by lvh** [comment]
New version is up on Clojars.

**Comment by lvh** [comment]
(Also bumped README version.)
