### ISSUE TITLE
Invalid value: `:runner midje` doesn't fail the build

### ISSUE THREAD

**Issue by vemv** [cloverage/cloverage#331]
If in a Lein map I specify:

```clj
:cloverage {:runner midje} ;; should have been :midje
```

I will see printed:

```
Invalid value: :runner ,  midje
```

and then the suite will proceed with the clojure.test runner, exiting with code 0.

This doesn't seem correct behavior for a test runner - I'd expect the handling of such a situation to be a fail-fast with non-zero exit code.

**Comment by lvh** [comment]
Agreed; it should exit immediately with an error.

**Comment by vemv** [comment]
Cheers, I'll give it a go
