### ISSUE TITLE
Cloverage doesn't support new clojure 1.12 array syntax

### ISSUE THREAD

**Issue by mikeananev** [cloverage/cloverage#347]
**How to reproduce:** just put new array syntax in code, e.g `(^[byte/1 int int] Arrays/copyOfRange (.getBytes "hello world") 0 3)`, then run tests with kaocha and enabled cloverage plugin.
**What I get:**  Invalid symbol: byte/1.
**What I expect:** no errors

**Workaround:** disable cloverage plugin.

**Comment by lvh** [comment]
Should be fixed by #349 and currently working on figuring out what a release looks like.
