### ISSUE TITLE
Support leiningen test selectors

### ISSUE THREAD

**Issue by voj** [cloverage/cloverage#54]
Leiningen test supports selectors for tests [(see documentation)](https://github.com/technomancy/leiningen/blob/2.4.3/src/leiningen/test.clj#L164) that allow for the inclusion or exclusion of tests when running `lein test`.

For example, we have some integration tests that we only want to run sometimes under (manually) controlled circumstances because they would cause mayhem otherwise. Cloverage simply runs all tests, getting clobbered in the process because of these special tests.

**Comment by MichaelBlume** [comment]
@ftomassetti did you ever come up with something that works? I'm happy to work on this if not, but I don't want to duplicate your work.

**Comment by ftomassetti** [comment]
Go ahead: I stopped because I was copying way too much code from lein-test and I got studi. Hope you can deliver this feature!

**Comment by msassak** [comment]
This would be really useful!

**Comment by positron** [comment]
Here is a workaround to skip specific namespaces: https://stackoverflow.com/a/50920753/683415

**Comment by rickschubert** [comment]
Can we please close this issue? #230 has fixed it.

**Comment by lvh** [comment]
Yup, thanks!
