### ISSUE TITLE
Coverage thresholds

### ISSUE THREAD

**Issue by kevinludwig** [cloverage/cloverage#99]
It would be nice to have support for coverage thresholds, so that if a configured threshold isn't met, the build can be failed. This is a fairly common coverage tool feature.

**Comment by lvh** [comment]
Hm, interesting. In my experience this has usually been the job of a tool that consumes output from the coverage tools -- Jenkins, or coveralls, or something. If we do do this, I'd like to keep it in the shape of something like that that's completely decoupled from cloverage itself.

**Comment by rm-hull** [comment]
I think maybe introducing some high/low watermark coverage thresholds for guidance only (and maybe _optionally_ failing the build, say, if issued with `lein cloverage check-threshold`) would be a good thing. 

This could be done by adding ANSI colour codes to the Cloverage summary table output, similar to how Istanbul (for javascript) reports a summary page with red/amber/green for the various different watermarks:

<img width="811" alt="karma-run" src="https://cloud.githubusercontent.com/assets/1915543/19419522/65de4f7e-93d1-11e6-916f-7357c7004f42.png">

IIRC the low watermark is 50% (below which reports as red), high watermark is 80% (above which reports as green), and between as amber.

**Comment by kevinludwig** [comment]
Maybe it's an additional plugin besides istanbul, but in the js ecosystem you can definitely specify a fail threshold yourself. I.e. fail if less than 90% coverage, for example.

**Comment by rm-hull** [comment]
So, I've got a feature branch (& PR brewing) with some changes to support this functionality:

Before:
<img width="505" alt="screen shot 2016-10-16 at 22 17 05" src="https://cloud.githubusercontent.com/assets/1915543/19420961/824c7a92-93ee-11e6-8bce-be1a22029ad2.png">

After:
<img width="471" alt="screen shot 2016-10-16 at 22 16 24" src="https://cloud.githubusercontent.com/assets/1915543/19420967/8e359eb0-93ee-11e6-98d0-a2a11c82565f.png">

_[This is part of a larger mission to extract all the reporting code into separate backend plugins]_

**Comment by arrdem** [comment]
Awesome!
